# Generated by Django 4.2.19 on 2025-06-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0002_batch_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='refered_doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
